"""fix nullable updated_at

Revision ID: 11280ec98bcc
Revises: 34cb4e604b49
Create Date: 2026-06-10 22:44:01.323267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '11280ec98bcc'
down_revision: Union[str, Sequence[str], None] = '34cb4e604b49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('conversations', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('roles', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('roles', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('conversations', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###
