"""initial

Revision ID: 211c8dd7245a
Revises: 
Create Date: 2026-06-01 18:25:42.824547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '211c8dd7245a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('conversations', 'system_prompt',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('conversations', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
    op.alter_column('conversations', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('messages', 'conversation_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('messages', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
    op.alter_column('messages', 'conversation_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('conversations', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('conversations', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
    op.alter_column('conversations', 'system_prompt',
               existing_type=sa.String(length=255),
               type_=mysql.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
